apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 476118517738.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 476118517738.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 54f406a1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
